version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=paddy
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: npm start
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=paddy
      - MONGO_INITDB_ROOT_PASSWORD=mypassword